CustomParam = ""

[Logger]
  FileName = "/mnt/logs/driver.log"
  LogLevel = "INFO"

[Clients]
  [Clients.Core]
    Address = "iot-core:57081"
    UseTLS = false
    CertFilePath = ""
    ClientId = ""
    Username = ""
    Password = ""

[Service]
  ID = "13021865"
  Name = "MQTT协议驱动-13021865"
  Activated = false
  [Service.Server]
    Address = "0.0.0.0:45211"
    UseTLS = false
    CertFile = ""
    KeyFile = ""
