CustomParam = ""

[Logger]
  FileName = "/mnt/logs/driver.log"
  LogLevel = "INFO"

[Clients]
  [Clients.Core]
    Address = "iot-core:57081"
    UseTLS = false
    CertFilePath = ""
    ClientId = ""
    Username = ""
    Password = ""

[Service]
  ID = "53525821"
  Name = "TCP协议驱动-53525821"
  Activated = false
  [Service.Server]
    Address = "0.0.0.0:39729"
    UseTLS = false
    CertFile = ""
    KeyFile = ""
