#version: "3"

networks:
  hummingbird:
    driver: bridge
services:
  mqtt-broker:
    image: registry.cn-shanghai.aliyuncs.com/winc-link/mqtt-broker:2.6
    container_name: mqtt-broker
    hostname: mqtt-broker
    restart: always
    ports:
      - "58090:58090"
    networks:
      - hummingbird
  ekuiper:
    image: registry.cn-shanghai.aliyuncs.com/winc-link/ekuiper:1.10.0-slim
    ports:
      - "127.0.0.1:9081:9081"
    container_name: ekuiper
    hostname: ekuiper
    restart: always
    user: root
    volumes:
      - ./kuiper/data:/kuiper/data
      - ./kuiper/log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mqtt-broker:58090"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    networks:
      - hummingbird
  iot-core:
    #image: docker.io/knight0209/iot-core:3.0
    #image: crpi-v6zzwgfx1g9e4e2d.cn-hangzhou.personal.cr.aliyuncs.com/knight0209/iot-core:3.0
    image: registry.cn-shanghai.aliyuncs.com/winc-link/hummingbird-core:v1.0
    container_name: iot-core
    restart: always
    hostname: iot-core
    ports:
      - "3000:3000"
      - "58081:58081"
      - "57081:57081"
    depends_on:
      - ekuiper
      - mqtt-broker
    volumes:
      - ./:/var/bin/hummingbird
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/configuration.toml:/etc/iot-core/configuration.toml
    networks:
      - hummingbird
